---
services:
  postgres:
    container_name: bytechef-postgres-prod
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-bytechef_secure_password_2024}
      - POSTGRES_USER=${POSTGRES_USER:-bytechef}
      - POSTGRES_DB=${POSTGRES_DB:-bytechef}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-bytechef}", "-d", "${POSTGRES_DB:-bytechef}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  bytechef:
    container_name: bytechef-app-prod
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - BYTECHEF_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-bytechef}
      - BYTECHEF_DATASOURCE_USERNAME=${POSTGRES_USER:-bytechef}
      - BYTECHEF_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-bytechef_secure_password_2024}
      - BYTECHEF_FEATURE_FLAGS=${BYTECHEF_FEATURE_FLAGS:-}
      - BYTECHEF_SECURITY_REMEMBER-ME_KEY=${BYTECHEF_REMEMBER_ME_KEY:-change_this_in_production_12345}
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "80:8080"
      - "443:8443"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  postgres_data:
    driver: local
